name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      GKI_DEV:
        description: 'GKI 分支，例如 android14-6.1-2024-10 或 android14-6.1'
        required: true
        default: 'android14-6.1-2024-10'
      KSU_BRANCH:
        description: '使用 SukiSU Ultra? (y/n)'
        required: true
        default: 'y'
      APPLY_SSG:
        description: '启用 SSG IO 调度? (y/n)'
        required: true
        default: 'y'
      APPLY_REKERNEL:
        description: '启用 RE-KERNEL? (y/n)'
        required: true
        default: 'y'
      APPLY_BBR:
        description: '启用 BBR 拥塞控制? (y/n/d)'
        required: true
        default: 'd'
      APPLY_KPM:
        description: '启用 KPM ? (y/n)'
        required: true
        default: 'y'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build.env from workflow inputs
        run: |
          mkdir -p local
          BUILD_ENV="local/build.env"
          GKI_DEV="${{ github.event.inputs.GKI_DEV }}"

          # 提取前两段生成 GKI_VERSION
          GKI_VERSION="gki-$(echo $GKI_DEV | cut -d'-' -f1-2)"

          cat > $BUILD_ENV <<EOF
          GKI_DEV=${GKI_DEV}
          GKI_VERSION=${GKI_VERSION}
          KSU_BRANCH=${{ github.event.inputs.KSU_BRANCH }}
          APPLY_SSG=${{ github.event.inputs.APPLY_SSG }}
          APPLY_REKERNEL=${{ github.event.inputs.APPLY_REKERNEL }}
          APPLY_BBR=${{ github.event.inputs.APPLY_BBR }}
          APPLY_KPM=${{ github.event.inputs.APPLY_KPM }}
          EOF

          echo ">>> build.env 内容:"
          cat $BUILD_ENV

      - name: Run build.sh
        run: |
          chmod +x local/build.sh
          ./local/build.sh
